### ISSUE TITLE
is utf8 not support java version of rivescript?

### ISSUE THREAD

**Issue by pureexe** [aichaos/rivescript-java#3]
or if it support how to enable it ?

**Comment by kirsle** [comment]
UTF-8 support was never added to the Java version of RiveScript. Adding it is easy though, I just need to find time to sit down and get it done.

UTF-8 support basically needs these things added:
* Add a utf8 flag to the constructor to turn on UTF-8 mode (default mode is off)
* Make sure all inputs (including files read from disk) are decoded into UTF-8
* Relax the syntax checking and string sanitization when UTF-8 mode is enabled.

If you feel up to the task you can make a pull request to add this. Here's examples of the changes for UTF-8 support in the [Python](https://github.com/aichaos/rivescript-python/commit/dde52360aa9452c53da0a92facea853b73adfbb4), [Perl](https://github.com/aichaos/rivescript-perl/commit/884708a4acf788a30274c62c3890d4587020a669) and [JavaScript](https://github.com/aichaos/rivescript-js/commit/0ea77415419b941ce6cadc3ab3743810104c2fe3) versions.

UTF-8 mode is still considered experimental where supported, because RiveScript wasn't designed from the ground up to consider UTF-8 (it was designed to replace AIML, which doesn't have much support for UTF-8 either), and there are certain caveats that I have yet to find a good solution for, such as user input containing punctuation characters (commas, etc.) for example the user saying "hello, how are you?" will not match the trigger `+ hello how are you` (and you shouldn't put a comma inside the trigger, it will mess with the regular expression engine)... so that's why it's not on by default.

**Comment by pureexe** [comment]
Thank you for your explain :D
