### ISSUE TITLE
Redirections with Macro broken on 0.8.0

### ISSUE THREAD

**Issue by UshakovVasilii** [aichaos/rivescript-java#39]
``` java
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import com.rivescript.RiveScript;
import com.rivescript.macro.Subroutine;

public class Test {

  public static class B implements Subroutine {
    @Override
    public String call(RiveScript rs, String[] args) {
      System.out.println("B");
      return "none";
    }
  }

  public static void main(String[] args) throws IOException {
    File f = new File("/tmp/test.rs");
    FileWriter w = new FileWriter(f);
    w.write("+ *\n");
    w.write("- end\n");
    w.write("+ hi\n");
    w.write("* <get v> != undefined => A\n");
    w.write("@ <call>b</call>\n");
   // w.write("- <call>b</call>\n"); // works as expected
    w.close();

    RiveScript rs = new RiveScript();
    rs.loadFile(f);
    rs.sortReplies();
    rs.setSubroutine("b", new B());
    rs.setUservar("test", "v", "V");
    System.out.println(rs.reply("test", "Hi"));
  }

}
```
I got output:
```
B
end
```
But condition is true. RiveScript ignore condition if redirection contain macro.

RiveScript version 0.8.0, works as expected on 0.7.2

**Comment by marceloverdijk** [comment]
Hi @UshakovVasilii,

I don't think it's related to Macro.

When I have this simplified example:

```
! version = 2.0

+ *
- end
                
+ hi
* 1 == 1 => A
* 1 != 2 => B
@ redirect
```

And I try to get a reply for 'Hi' I also get back 'end'.

In the RiveScript WD spec I don't see any mention of using a redirect (`@`) as a condition.

Also when I try same example on RiveScript playground I get the same result.
See for yourself: https://play.rivescript.com/s/lRvCBch59W

Maybe this was working in < 0.8.0 unexpectedly. What do you think @kirsle?

**Comment by kirsle** [comment]
Yeah; all (iirc) of the implementations I wrote treat the `@Redirect` command as a very high priority item: each trigger can have *at most*\* one `@` command (multiple `@`'s result in them overwriting each other, as they're stored as a string and not an array).

After a trigger match has been found, the first thing RiveScript does is check for a redirect and follow it. The checks for conditions and replies would happen later in the code, and so a trigger with an `@Redirect` would ignore any conditions or replies and immediately follow the redirect.

You could get the behavior you want by using an inline redirect tag instead of the redirect command, i.e.

```
! version = 2.0

+ *
- end
                
+ hi
* 1 == 1 => A
* 1 != 2 => B
- {@redirect}
```

https://play.rivescript.com/s/sf3oTsI3B1

\* My first pass in the Java implementation supported multiple redirects (putting them on an array and picking one randomly), as [listed here](https://github.com/aichaos/rivescript-wd/blob/349f3f577380fe3a647951f9406be35a8e127b25/Pending%20Changes.md#multiple-redirects), but I didn't keep that behavior in the other implementations I wrote later.

**Comment by marceloverdijk** [comment]
Thanks @kirsle that explains why this got lost from 0.7.x towards 0.8.0.

**Comment by UshakovVasilii** [comment]
Got it, thanks for explanation!

**Comment by marceloverdijk** [comment]
Will close this one and mark it as invalid as it's not related Macro's.
