### ISSUE TITLE
Macro split one argument to multiple arguments by space

### ISSUE THREAD

**Issue by UshakovVasilii** [aichaos/rivescript-java#40]
``` java
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

import com.rivescript.RiveScript;
import com.rivescript.macro.Subroutine;

public class RsTest {

  public static class F implements Subroutine {
    @Override
    public String call(RiveScript rs, String[] args) {
      for (String arg : args)
        System.out.println(arg);
      return "";
    }
  }

  public static void main(String[] args) throws IOException {
    File f = new File("/tmp/test.rs");
    FileWriter w = new FileWriter(f);
    w.write("! version = 2.0\n\n");
    w.write("+ *\n");
    w.write("- <call>f <get v></call>\n");
    w.close();

    RiveScript rs = new RiveScript();
    rs.loadFile(f.getAbsolutePath());
    rs.sortReplies();
    rs.setSubroutine("f", new F());
    rs.setUservar("test", "v", "a b");
    System.out.println(rs.reply("test", "Hi"));
  }

}
```
I got output:
```
a
b
```
I expect that macro get one argument `a b`.

Also if method `call` return `null` when NullPointerException thrown. To get `undefined` result `call` function should return empty string. Is it OK?

It reproduced on 0.7 and 0.8

**Comment by marceloverdijk** [comment]
PS: you don't have to write the `test.rs` file, you can also use `rs.stream(String[])` to directly load the RiveScript code :-)

**Comment by marceloverdijk** [comment]
I will provide a fix for `Subroutines` and `ObjectHandler` that return `null`. In that case I will treat it as if the macro just returned `""`.

Both `""` (or `null` after my the fix) will *not* result in automatically the string `undefined` in the reply. If you want that, you should return `"undefined"` from the macro.
Another option is that in case the macro returns `null` I would assign `"undefined"` instead of `""`.
@kirsle what do you think, as I this currently also not the case for the Go impl and want to keep them in sync as much as possible.

Related to getting 2 arguments instead of 1 you expected.
The `<get v>` is just replaced by `a b ` resulting in `- <call>f a b</call>` which in turn results in 2 arguments. Maybe we should think about a way to explicitly start and end argument values. E.g. `- <call>f "a b"</call>` and in your case that would be `- <call>f "<get v>"</call>`. Again @kirsle what is your opinion?

**Comment by marceloverdijk** [comment]
@UshakovVasilii after I discuss the options with @kirsle I will make a `0.8.1` release asap. I have another pending bugfix related to Google AppEngine hosted environment anyway.

**Comment by marceloverdijk** [comment]
`Subroutine`s and `ObjectHandler`s returning `null` will be treated as empty string `""` (already fixed on `master` branch.

I will also make a change so Marco arguments can be quoted (using a `"`). 
This would make this possible:
`- <call>f "a b" c d</call>`
which would result in 3 args: "a b", "c" and "d"

And using user vars it would look like: `- <call>f "<get v>"</call>`
(assuming the subroutine `f` returns `a b`.
